server:
  port: 6312
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brunhilde?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 888888
    driver-class-name: com.mysql.jdbc.Driver
    #初始化数据
    sql-script-encoding: UTF-8
    schema: classpath*:schema.sql
    data: classpath*:data.sql
    continue-on-error: true
    initialization-mode: always #never,always
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true


